# Generated by Django 2.2.4 on 2019-11-02 06:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 11, 2, 6, 4, 57, 500145, tzinfo=utc), verbose_name='date updated'),
            preserve_default=False,
        ),
    ]
