# Generated by Django 2.2.4 on 2019-09-03 23:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20190903_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forum',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='thread',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='thread',
            name='title',
            field=models.CharField(default='Title', max_length=500),
            preserve_default=False,
        ),
    ]
